In [14]:
with open("Data/input.txt", "r") as f:
    lines = f.read()

In [15]:
len(lines)

1115394

In [17]:
print(lines[:10])

First Citi


In [25]:
chars = sorted(list(set(lines)))
size = len(chars)
print(''.join(chars))
size


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz


65

In [66]:
class Coding:
    def encode(s, chars = chars):
        code = []
        for char in s:
            for char1 in chars:
                if char == char1:
                    code.append(chars.index(char1))
        return (code)
            
        
    def decode(s_coded, chars = chars):
        decode = []
        for char in s_coded:
            for char1 in chars:
                if char == chars.index(char1):
                    decode.append(char1)
        return (''.join(decode))

print(Coding.encode("hii there"))
print(Coding.decode(Coding.encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [67]:
text = Coding.encode(lines)
print(text[:10])

[18, 47, 56, 57, 58, 1, 15, 47, 58, 47]


In [68]:
import torch
data = torch.tensor(Coding.encode(lines), dtype = torch.long)
print(data.shape, data.dtype)
print(data[:10])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47])


In [70]:
print(data[:100])

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [72]:
n = int(len(data) * 0.9)
train = data[:n]
val = data[n:]
print('train:', train.shape, 'val:', val.shape)

train: torch.Size([1003854]) val: torch.Size([111540])


In [85]:
block_size = 8
train[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [86]:
x = train[:block_size]
y = train[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context}, the target is {target}")

when input is tensor([18]), the target is 47
when input is tensor([18, 47]), the target is 56
when input is tensor([18, 47, 56]), the target is 57
when input is tensor([18, 47, 56, 57]), the target is 58
when input is tensor([18, 47, 56, 57, 58]), the target is 1
when input is tensor([18, 47, 56, 57, 58,  1]), the target is 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]), the target is 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]), the target is 58


In [112]:
torch.manual_seed(1337)
block_size = 8
batch_size = 4

def get_batch(split):
    data = train if split == 'train' else val
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print("data:", '\n', xb.shape, xb.dtype, '\n', xb, '\n', yb.shape, yb.dtype, '\n', yb, '\n')

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f"when input is {context}, the target is {target}")



data: 
 torch.Size([4, 8]) torch.int64 
 tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]]) 
 torch.Size([4, 8]) torch.int64 
 tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]]) 

when input is tensor([24]), the target is 43
when input is tensor([24, 43]), the target is 58
when input is tensor([24, 43, 58]), the target is 5
when input is tensor([24, 43, 58,  5]), the target is 57
when input is tensor([24, 43, 58,  5, 57]), the target is 1
when input is tensor([24, 43, 58,  5, 57,  1]), the target is 46
when input is tensor([24, 43, 58,  5, 57,  1, 46]), the target is 43
when input is tensor([24, 43, 58,  5, 57,  1, 46, 43]), the target is 39
when input is tensor([44]), the target is 53
when input is tensor([44, 53]), the target is 56
when input is tensor